### PR TITLE
visitors and github added #354 done

### LINKED ISSUE #354: [Feature Request]: adding a total visitors and star my repo button on footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

[Feature Request]: adding a total visitors and star my repo button on footer

### Use Case

your repo got more stars and total visitors show on website.

### Benefits

_No response_

### Add ScreenShots

fith
visiting

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
# Title and Issue number 

Title : Total visitors and Star us button added in github

Issue No. : #354

Code Stack : React

Close #354

# Video (mandatory)
visi2

# Checklist:

- [ X] I have mentioned the issue number in my Pull Request.
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X ] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***

- [X ] I'm a GSSOC-EXT contributor
- [X ] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@VinayLodhi1712 update in latest footer

**Comment by VinayLodhi1712** [comment]
now you can check @jeevan10017 
visit2
visit

**Comment by jeevan10017** [comment]
@VinayLodhi1712, resolve conflicts and make the footer as you showed in this upper. Visitors count background colour amk=tch to the dark.

**Comment by VinayLodhi1712** [comment]
Visitors count background colour amk=tch to the dark. what does this mean

**Comment by jeevan10017** [comment]
>Visitors count background colour amk=tch to the dark. what does this mean 

sorry typing error, make that visitors count the background to dark, match the footer theme

**Review by jeevan10017 — APPROVED** [review]

**Pull request merged**
