### PR TITLE
Feature/aboutus : about us page redesigned #70 solved

### LINKED ISSUE #70: [Feature Request]: Making about us page good looking and also add some dummy stats showing on scroll up animation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

About us page UI is not good looking so i want to redesing it with same content also want to show dummy stats like total user and all on scroll up animation on about us page

### Use Case

Good UI design

### Benefits

_No response_

### Add ScreenShots

about page ui

Uploading 20241006142647.mp4…

plz add level on it so i can start working on it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
#70  done
Title : About us page redesigned

Issue No. : #70 

Code Stack : Mainy React with Css

Close #70

# Video (mandatory)
statsshow

https://github.com/user-attachments/assets/20103766-f664-41b7-a80a-1801d48c728a

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
If you like design can you make it level 2.

***Are you contributing under any Open-source programme?***

- [ X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by Sami3160 — CHANGES_REQUESTED** [review]
1. add vector images of orange-flame color theme, you can get them form icons8 or font awesome and also use proper png images,
2. and again use verdana font or something modern use default font,
3. dont use that red border box, make it look modern as well as simplistic , okay? 
4. that stats part, use individual cards for each stat, instead of use a container like div 
5. also add that stats part after "What we offer" 
6. use little cards for that our mission and our vision
7. on small window width have 2x2 card for stats instead of one single column of stats(responsiveness)

i appreciate ur hard work on this contribution but you current changes are not much good and visually appealing, try other ui/ux, remember to make it simplistic and modern!

**Comment by VinayLodhi1712** [comment]
okay i can start work on changes everything i got it but what you want in point 1 I dont understand.

**Comment by jeevan10017** [comment]
@VinayLodhi1712, kindly make minor changes
  1. change the colouring of cards and text in dark mode, too.
  2.  join fit flex button hovering- change blue to dark orange/ gradient
  3.  Link the Join fit flex button to the register page.

**Comment by VinayLodhi1712** [comment]
so i have made changes according to you. Check it once.
about us2
about usmore

https://github.com/user-attachments/assets/b97d129c-a944-4383-8cff-ad3cde5b6366


So i have to work 2-3 times and have to implement in dark mode also can increase the level of this issue as i have to work a lot in this.

**Comment by jeevan10017** [comment]
@VinayLodhi1712 yeah i will definitely increase the level. But we need quality work. As use raised issues for enhancement for existing ones. 
During dark mode the white cards did not seem to be good. Make it a black-gray fade which is ever suitable.

**Comment by VinayLodhi1712** [comment]
ok any other changes can you plz tell me now 
also this is the color you want right 
background: linear-gradient(135deg, #000000, #444444); /* Black to dark gray gradient */ in card during dark mode.

**Comment by jeevan10017** [comment]
> darkgrewy
> 
> dark grey is not looking good as 1st card. and 2nd one is light grey which i think will look good and 3rd and 4th one is white color card. So which color i implement in card for dark background.

For dark 1st one.
With white text.

**Comment by jeevan10017** [comment]
> > darkgrewy
> > 
> > dark grey is not looking good as 1st card. and 2nd one is light grey which i think will look good and 3rd and 4th one is white color card. So which color i implement in card for dark background.
> 
> For dark 1st one(should differ with the background color).
> With white text.
>

**Comment by jeevan10017** [comment]
> > > darkgrewy
> > > 
> > > dark grey is not looking good as 1st card. and 2nd one is light grey which i think will look good and 3rd and 4th one is white color card. So which color i implement in card for dark background.
> > 
For dark 1st one(should differ with the background color).
 With white text.

**Comment by VinayLodhi1712** [comment]
you mean in dark mode -
1.  background: linear-gradient(135deg, #000000, #444444); this background on card.
2. and have white color text right. 
3. and this type of card should implement to all available card present on about us page.

**Comment by Sami3160** [comment]
> you mean in dark mode -
> 
>     1. background: linear-gradient(135deg, #000000, #444444); this background on card.
> 
>     2. and have white color text right.
> 
>     3. and this type of card should implement to all available card present on about us page.

yes,

**Comment by VinayLodhi1712** [comment]
@Sami3160 and @jeevan10017 sir i have done this now can you plz merge it and also increase level for it.

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
why all were commiting pakage-lock.json

**Comment by Sami3160** [comment]
> why all were commiting pakage-lock.json

Kya hua

**Comment by VinayLodhi1712** [comment]
can you merge it or is there more changes i have to do and plz increase level.

**Comment by jeevan10017** [comment]
@VinayLodhi1712 remove package-lock.json in this PR

**Comment by VinayLodhi1712** [comment]
i am creating new pull request because it is deleted by me forcefully so i am creating new pull request and plz see changes there.

**Pull request closed without merging**
