### PR TITLE
fixed faq issue

### LINKED ISSUE #347: [Bug]: FAQs answers not visible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The FAQs answers are not visible when we try to see it

### Expected behavior

The answers should be shown 

### Add ScreenShots

image

image

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Gauravtb2253**
# Title and Issue number 

Title : FAQs answers not visible

Issue No. : #347 

Code Stack : 

Close #347 

image

I have fixed the faq issue 
Now the faq answers are visible
Also there were some issues in footer regarding tags
I also solved it

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [ ] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
resolve conflicts

**Comment by Gauravtb2253** [comment]
any updates

**Review by jeevan10017 — APPROVED** [review]

**Comment by jeevan10017** [comment]
@Gauravtb2253 Sorry for the late reply, fix conflicts

**Comment by Gauravtb2253** [comment]
done

**Pull request merged**
