### PR TITLE
Reviews Sections..

### LINKED ISSUE #401: [Feature Request]: Review Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

other customer canreview the services that you provide..

### Benefits

New Customer ca get easly idea about your services..

### Add ScreenShots
https://github.com/user-attachments/assets/32aa05ae-5a13-4280-bf7b-5953bac4da78

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
# Title and Issue number 
Title : Review Section

Issue No. : 401

Close #401 

# Video (mandatory)
https://github.com/user-attachments/assets/fdae5c23-fccf-441d-a3b5-b52ea539c6ff

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context**
added reviews section..

***Are you contributing under any Open-source programme?***
- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Meetpidev** [comment]
@jeevan10017 Please review PR...

**Comment by Meetpidev** [comment]
@jeevan10017 Review PR

**Comment by jeevan10017** [comment]
no need of it, existing one is good.

**Comment by Meetpidev** [comment]
@jeevan10017 there should be review section.. from that customer can get better ideas..

**Comment by Meetpidev** [comment]
@jeevan10017 if you want then i can make design better of it

**Pull request closed without merging**
