### PR TITLE
Backend Of Reviews

### LINKED ISSUE #402: [Feature Request]: Backend implementation for add,edit and delete review
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Backend implementation for add,edit and delete review 

### Use Case

To display reviews...

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Meetpidev**
Title : Backend Implemenation of Reviews.

Issue No. : #402 

Code Stack : 

Close #402
image
image
image
image
same for the delete also.

# Checklist:
- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Meetpidev** [comment]
@GAVINESHWAR Requested To Review PR..

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR..

**Comment by Meetpidev** [comment]
@GAVINESHWAR Requested to review PR

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR..

**Comment by jeevan10017** [comment]
@Meetpidev I have waited for this review because you have not yet linked the image/video for reference. because it disabled the deploy preview

**Comment by Meetpidev** [comment]
@jeevan10017 Please Review Again...

**Comment by jeevan10017** [comment]
@Meetpidev send a video reference

**Pull request closed without merging**
