### PR TITLE
Update Footer and About Us page || Issue 13 & 14

### LINKED ISSUE #13: About Us Page Updation and Footer Logo Updation of Twitter to X
I have noticed the footer section is not very attractive, user-friendly, and also the wrong logo (twitter logo) which is now X.

image

Also I have noticed that the About us page is also not that much informative and well structured

image

@Kritika30032002 @Sami3160 @jeevan10017
please assign this task to me.

### PR DESCRIPTION
**Pull request by Shariq2003**
# Title and Issue number 
Title : Update Footer and About Us page

Issue No. : 13 & 14

Code Stack : Same as Base Code Stack

Close #13  & #14

# Video (mandatory)

https://github.com/user-attachments/assets/8d1badf9-02bf-4743-8c5d-23499c9506cb

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Sami3160** [comment]
> # Title and Issue number
> 
> Title : Update Footer and About Us page
> 
> Issue No. : 13 & 14
> 
> Code Stack : Same as Base Code Stack
> 
> Close #13 & #14
> # Video (mandatory)
> Issue.13.and.14.mp4
> # Checklist:
> 
>     * [x]  I have mentioned the issue number in my Pull Request.
> 
>     * [x]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [x]  I have created a helpful and easy to understand `README.md` if its a new page/tech stack
> 
>     * [x]  I have gone through the  `contributing.md` file before contributing
> 
> 
> **Additional context (Mandatory )**
> 
> _**Are you contributing under any Open-source programme?**_
> 
>     * [x]  I'm a GSSOC-EXT contributor
> 
>     * [ ]  I'm a HACKTOBERFEST contributor

excellent work!

**Comment by Shariq2003** [comment]
@Sami3160 sir please add levels to this PR so that it will reflect into my count

**Review by jeevan10017 — COMMENTED** [review]
Good work !

**Comment by Shariq2003** [comment]
Thanks @jeevan10017 Sir

**Comment by Shariq2003** [comment]
@jeevan10017 Sir, could you please also let me know any other changes or issues that I can fix

**Comment by jeevan10017** [comment]
Can you please change the design and layout of the footer? It's not very attractive.
and also follow the entire website with 1 or 2 font family

**Comment by jeevan10017** [comment]
> @jeevan10017 Sir, could you please also let me know any other changes or issues that I can fix


Can you please change the design and layout of the footer? It's not very attractive.
and also follow the entire website with 1 or 2 font family

**Comment by Shariq2003** [comment]
@jeevan10017 Sir, Can I raise an Issue in which I will fix the whole website, by fixing the font family, layout of footer and also the Cards of Plans on the Home page and etc.
That will fix the whole structure of the website

**Comment by jeevan10017** [comment]
> @jeevan10017 Sir, Can I raise an Issue in which I will fix the whole website, by fixing the font family, layout of the footer and also the Cards of Plans on the Home page and etc. That will fix the whole structure of the website

Raise issues one after another because others are also working on the same page, merge conflicts can occur, and font family should see at last.

**Comment by Shariq2003** [comment]
So what should I do sir.

**Comment by jeevan10017** [comment]
> So what should I do sir. Should I have to raise an Issue for Making the whole AboutUs Page

I believe you have already completed it right?, This merged PR

**Comment by Shariq2003** [comment]
> > So what should I do sir. Should I have to raise an Issue for Making the whole AboutUs Page
> 
> I believe you have already completed it right?, This merged PR

Yes sir I have updated the About Us page, but if you want to make it more attractive or want any change I can change sir,

**Comment by jeevan10017** [comment]
give a idea or reference pic, what you are going to add

**Comment by Shariq2003** [comment]
Okay I will share the ss that I can make to enhance the structure of the about us section even more better

**Comment by jeevan10017** [comment]
> Okay I will share the ss that I can make to enhance the structure of the about us section even more better

Ok, create a new enhancement issue.

**Comment by Shariq2003** [comment]
> > Okay I will share the ss that I can make to enhance the structure of the about us section even more better
> 
> Ok, create a new enhancement issue.

okay sir

**Comment by Sami3160** [comment]
> Okay I will share the ss that I can make to enhance the structure of the about us section even more better

hey that footer section is taking some extra space, that logo part, i checked on many browsers, seems like its styling issue 
Screenshot at 2024-10-03 18-22-01
look at that, try to fix it and make another commit

**Comment by Shariq2003** [comment]
@Sami3160 sir, okay, will fix this by EOD

**Comment by Shariq2003** [comment]
> > Okay I will share the ss that I can make to enhance the structure of the about us section even more better
> 
> hey that footer section is taking some extra space, that logo part, i checked on many browsers, seems like its styling issue Screenshot at 2024-10-03 18-22-01 look at that, try to fix it and make another commit


@Sami3160 , i have checked that this issue is not caused by the changes that I made, it was also there before, when I checked the code of the footer before my merge, the issue was still there,
You can also check by just comparing or run the previous code of the footer.
Still i am working on it to fix.

**Comment by Shariq2003** [comment]
> Good work !

@jeevan10017 please add the label for hacktoberfest to it, so that it will reflect into my account

**Pull request merged**
