### PR TITLE
Log In broken link from register page bug solved : Issue no #49

### LINKED ISSUE #49: [Bug]: Log In broken link from register page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Encountered a broken link on the Register page when attempting to navigate to the Log In page. Clicking the "Sign In" button results in a "Page Not Found" error, displaying the message: "Looks like you've followed a broken link or entered a URL that doesn't exist on this site." This issue prevents users from accessing the login functionality, hindering the registration process.

### Expected behavior

When a user clicks on the "Sign In" button from the Register page, they should be redirected to the Log In page without any errors. The Log In page should load correctly, allowing users to enter their credentials and access their accounts.

### Add ScreenShots

Screenshot 2024-10-04 155441
Screenshot 2024-10-04 155515

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
# Title and Issue number 

Title : [Bug]: Log In broken link from register page.

Issue No. : #49 

Code Stack : 

Close #49 

# Video (mandatory)

https://github.com/user-attachments/assets/ebd1ae70-af10-44bb-8b8d-12dde29ba149

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by AbhijitMotekar99** [comment]
Hey @Sami3160 
Thank you for your feedback! I understand the importance of adding the debouncing feature for a better user experience. I'll definitely give it a try and work on incorporating it into the registration page.

If I encounter any issues or can't add it for some reason, could you please merge my previous PR as level 1? Do I need to create a new issue for the debouncing feature, or should I include it in the existing PR?

**Comment by Sami3160** [comment]
> Hey @Sami3160 Thank you for your feedback! I understand the importance of adding the debouncing feature for a better user experience. I'll definitely give it a try and work on incorporating it into the registration page.
> 
> If I encounter any issues or can't add it for some reason, could you please merge my previous PR as level 1? Do I need to create a new issue for the debouncing feature, or should I include it in the existing PR?

just include it in existing pr

**Comment by AbhijitMotekar99** [comment]
added a debouncing feature.

**Comment by AbhijitMotekar99** [comment]
Which changes do you need ?

**Review by Sami3160 — CHANGES_REQUESTED** [review]
excellent work! just fix one thing, that password field, looks like you removed ```type={showPassword ? "text" : "password"}``` from password field, so hiding and showing password and confirm password  is not properly working...
look below
image
 just fix that

**Comment by AbhijitMotekar99** [comment]
Hey @Sami3160 
I have add line type={showPassword ? "text" : "password"}

can you also add hactoberfest-accepted label

**Comment by Sami3160** [comment]
> Hey @Sami3160 I have added line type={showPassword ? "text" : "password"}
> 
> can you also add hactoberfest-accepted label

nice, just one little change, make both password fields and their eye mark individual,
clicking on one eye mark is showing both password fields, thats it

**Comment by AbhijitMotekar99** [comment]
I solved "make both password fields and their eye mark individual" this problem.
Now all is done PR is ready to merged

Resgister 1

Register 2

**Comment by AbhijitMotekar99** [comment]
Hey @Sami3160 
I believe I have resolved several issues in this PR, including the show password bug, along with other improvements. I’ve dedicated significant time and effort to this contribution, and I kindly request that you consider upgrading this PR to Level 3.

Thank you for your understanding and support.

Best regards,
Abhijit

**Comment by Sami3160** [comment]
> Hey @Sami3160 I believe I have resolved several issues in this PR, including the show password bug, along with other improvements. I’ve dedicated significant time and effort to this contribution, and I kindly request that you consider upgrading this PR to Level 3.
> 
> Thank you for your understanding and support.
> 
> Best regards, Abhijit

my friend, you did well, but the level of word is decided by the amount of changes and quality of work not by amount of time spent, which in you your case is not enough for lvl3, but bhai kya hi dikkat hai, lelo lvl3 mera bhi kya hai jayega

nice contribution you did their!!

**Comment by AbhijitMotekar99** [comment]
Thank you @Sami3160 for your support.

**Pull request merged**
