### PR TITLE
Navbar Enhance, Services Page Redesigning, ContactUS Theme Fixes, Nam… | Issue #182

### PR DESCRIPTION
**Pull request by Shariq2003**
Completed #182 

## Fixes :

1. Redesign the Whole Page of services.
2. Navbar Enhancements.
3. Contact Us page Theme Issue Fixes.
4. Services Modal's Name Field occur twice Fixed. 

# Video (mandatory)

https://github.com/user-attachments/assets/5f442799-9a90-4bc2-b902-f83a408e1b7e

https://github.com/user-attachments/assets/f30b34de-f26b-484d-a3e9-e4c91061a822

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Shariq2003** [comment]
@jeevan10017 please review and merge

**Comment by Shariq2003** [comment]
@jeevan10017 please review and merge

**Comment by jeevan10017** [comment]
@Shariq2003 Resolve merge conflicts and change the font style on the service page to the website font family.

**Comment by Shariq2003** [comment]
> @Shariq2003 Resolve merge conflicts and change the font style on the service page to the website font family.

@jeevan10017 please review and merge

**Review by jeevan10017 — APPROVED** [review]

**Comment by Shariq2003** [comment]
@jeevan10017 i have fixed multiple issues along with the redesigning of services page

**Pull request merged**
