### PR TITLE
Add Subscribe to the platform

### LINKED ISSUE #308: [Feature Request]: Subscribe to the Platform
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

users should get a email for confirmation when they subscribe the platform. This is a must feature for having for a website like this.
Also it will help users to keep track for the updates for the services on the website.

### Use Case

This is a must feature for having for a website like this.
Also it will help users to keep track for the updates for the services on the website.

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-10-22 132457

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Title and Issue number 

Title : Subscribe to the platform

Issue No. : #308 

Code Stack : Node.js with express

Close #308

# Video (mandatory)
Screenshot 2024-10-23 164005
Screenshot 2024-10-23 164310
WhatsApp Image 2024-10-23 at 4 49 52 PM

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Sami3160** [comment]
> # Title and Issue number
> 
> Title : Subscribe to the platform
> 
> Issue No. : #308
> 
> Code Stack : Node.js with express
> 
> Close #308
> # Video (mandatory)
> 
> Screenshot 2024-10-23 164005 Screenshot 2024-10-23 164310 WhatsApp Image 2024-10-23 at 4 49 52 PM
> # Checklist:
> 
>     * [x]  I have mentioned the issue number in my Pull Request.
> 
>     * [x]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [x]  I have created a helpful and easy to understand `README.md` if its a new page/tech stack
> 
>     * [x]  I have gone through the  `contributing.md` file before contributing
> 
> 
> **Additional context (Mandatory )**
> 
> _**Are you contributing under any Open-source programme?**_
> 
>     * [x]  I'm a GSSOC-EXT contributor
> 
>     * [x]  I'm a HACKTOBERFEST contributor

the app was supposed to be build with only one frontend server and no dedicated backend for any task, need to ask OpenCodeCrafters lead about this, you can wait till i got response

**Review by Sami3160 — CHANGES_REQUESTED** [review]
instead of using express, try using emailjs on frontend, this project does not supposed to have different backend server, so try implementing same feature in react

**Comment by haseebzaki-07** [comment]
It's just a API for the service there is not data stored in the backend, so functionality is same as emailjs , also I worked on this issue because I was assigned for it, Please consider. @Sami3160

**Comment by Sami3160** [comment]
> It's just a API for the service there is not data stored in the backend, so functionality is same as emailjs , also I worked on this issue because I was assigned for it, Please consider. @Sami3160 

I completely agree with you friend, but upar se orders hai, ki project sirf react me karna hai...
I do respect ur work on this pr but I can't change any decision from my side
Try using emailjs from frontend

**Comment by haseebzaki-07** [comment]
Okay @sami I will do it

**Comment by haseebzaki-07** [comment]
hey @Sami3160 removed the API and implemented Emailjs in the frontend.

WhatsApp Image 2024-10-28 at 4 14 23 PM


https://github.com/user-attachments/assets/f032d311-edda-403a-8051-e69c06d64c3d


@Sami3160 please increase the level of the PR, it was double task for me.

**Review by Sami3160 — APPROVED** [review]

**Comment by haseebzaki-07** [comment]
@sami please increase the level!!

**Comment by haseebzaki-07** [comment]
@GAVINESHWAR @Sami3160 after all this work only level 1???.
It was really exhausting for me

**Comment by jeevan10017** [comment]
@haseebzaki-07 who said you to remove in the footer?

**Comment by haseebzaki-07** [comment]
@jeevan10017 that change came when I updated my branch, please add back the labels

**Comment by jeevan10017** [comment]
@haseebzaki-07 peace hai

**Comment by haseebzaki-07** [comment]
@jeevan10017 thank you

**Pull request merged**
