### PR TITLE
Added autoscrollable responsive success

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
# Title and Issue number 

Title : Enhance the UI of success story 

Issue No. : #292 

https://github.com/user-attachments/assets/a18516b9-edf8-48d2-8e5b-b45845660608

Screenshot 2024-10-21 232937

 Added a auto scrollable responsive good looking success story section 
 
Can i get level 3 for it as it required lot of effort to build it if not level 3 atleast level 2 !
if you want any improvement just tell me i will resolve it ASAP

# Checklist:

- [ ✅] I have mentioned the issue number in my Pull Request.
- [✅ ] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [ ✅] I have gone through the  `contributing.md` file before contributing

 

***Are you contributing under any Open-source programme?***

- [ X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by jeevan10017 — COMMENTED** [review]
@Sawan-Kushwah  Design is good. But try to change the coloring. and Header is missing while scrolling.

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 any prefered color? Or I try something?

**Comment by jeevan10017** [comment]
@Sawan-Kushwah you can try something 
or 
white/dark background to to toggle, orange yellow gradient cards

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 check it once !?
image

**Comment by jeevan10017** [comment]
@Sawan-Kushwah  good, keep more orange gradient. And see, why is your css conflicting with the header(getting disappeared) while scrolling down.

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 will you please tell me which header is getting disappeared i don't see any

**Comment by Sawan-Kushwah** [comment]
image


@jeevan10017 Done with the required changes!!

**Comment by jeevan10017** [comment]
> @jeevan10017 will you please tell me which header is getting disappeared i don't see any 

Navbar

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 do you want Navbar should be sticky as we scroll down then also it's should visible?

**Comment by jeevan10017** [comment]
> @jeevan10017 do you want Navbar should be sticky as we scroll down then also it's should visible at top? 

Yeah,
Or if you know do this thing.
When you scroll down the navbar should disappear and when you scroll up it should appear.

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/937a10c7-75f6-48c8-93a1-1b25c6ef9919

@jeevan10017 Done

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 can I get higher level on This PR please

**Comment by jeevan10017** [comment]
> @jeevan10017 can I get higher level on

Level you are expecting?

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 no level on PR why??

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 please add level tag else I don't get any points

**Comment by jeevan10017** [comment]
Yeah i am waiting for your expectations

**Comment by Sawan-Kushwah** [comment]
Thanks for adding level 2 ☺️

**Pull request merged**
