### PR TITLE
Implemented Forgot Password Page

### LINKED ISSUE #285: [Feature Request]: Implementation of "Forgot Password" Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Forgot Password" feature allows users who have forgotten their passwords to reset them, enhancing user experience and account security securely. This feature minimizes user frustration and increases the likelihood of user retention by providing a straightforward recovery process.

### Use Case

"Forgot Password" feature not only enhances user experience but also contributes to the security and credibility of the project. 

### Benefits

To enhance user experience and security by allowing users to reset their passwords if they forget them.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by SRV30**
Implementation of "Forgot Password" Page and #285 

Title : Implementation of "Forgot Password" Page

Issue No. : #285 

Code Stack : 

-                    **Frontend Code:**
-                                  ⚪The Forgot Password form with fields for email input and submission.
- 
-                    **Backend Code:**
-                                  ⚪Call Firebase’s sendPasswordResetEmail function to initiate the password reset process.
- 

Close #285 

# Video (mandatory)

https://github.com/user-attachments/assets/3df782f2-dde3-4ad9-85dd-794ca98eede6

# Images
1.
image

2. 
image

3.
image

4.
image

5.
image

6.
image

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by SRV30** [comment]
@GAVINESHWAR, please review my pt

**Comment by SRV30** [comment]
please review my pr

**Comment by SRV30** [comment]
@jeevan10017 please look this

**Comment by jeevan10017** [comment]
@SRV30 Good work, but can you see that the present registration is not working? fix it

**Comment by SRV30** [comment]
@jeevan10017 thank you

**Pull request merged**
