### PR TITLE
Calorie Tracker Isuue no. 244

### PR DESCRIPTION
**Pull request by justhappyuknow**
# Title and Issue number 

Title :

Issue No. :  244

Code Stack :  Tracker.jsx (JS)

Close #<issue_no>

# Video (mandatory)

image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
image
@justhappyuknow Fit it, Try to keep it somewhere instead of Hompage. Or create a page and link it in a footer.

**Comment by justhappyuknow** [comment]
> image @justhappyuknow Fit it, Try to keep it somewhere instead of Hompage. Or create a page and link it in a footer.

You will have to use the API key which I have removed from the codebase for fetching the data, and yes will link it in footer

**Comment by jeevan10017** [comment]
> > image @justhappyuknow Fit it, Try to keep it somewhere instead of Hompage. Or create a page and link it in a footer.
> 
> You will have to use the API key which I have removed from the codebase for fetching the data, and yes will link it in footer

From where you have got that API Key?

**Comment by jeevan10017** [comment]
@justhappyuknow Create in it in a new page and link it to the footer

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@justhappyuknow Create in it in a new page and link it to the footer

**Comment by justhappyuknow** [comment]
> > > image @justhappyuknow Fit it, Try to keep it somewhere instead of Hompage. Or create a page and link it in a footer.
> > 
> > 
> > You will have to use the API key which I have removed from the codebase for fetching the data, and yes will link it in footer
> 
> From where you have got that API Key?

calorieninjas.com

**Pull request merged**
