### PR TITLE
Update success design and add animation

### LINKED ISSUE #130: Add animation to Success Stories
**Contributor Information**
Please check if you are a contributor from:
- [✔️ ] GSSoC-ext
- [✔️ ] Hacktoberfest

I can add animation to success story cards for better Visual Appeal and Engagement.

### PR DESCRIPTION
**Pull request by AmanKumar1115**
# Title and Issue number 

Title :

Issue No. : #130 

Code Stack : 

Close #130

https://github.com/user-attachments/assets/c36652da-6ba6-4f8d-8adb-e2940598c511

# Video (mandatory)

# Checklist:

[ ✔️] I have mentioned the issue number in my Pull Request.
[ ] I have commented my code, particularly in hard-to-understand areas
[ ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
[ ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [✔️ ] I'm a GSSOC-EXT contributor
- [✔️ ] I'm a HACKTOBERFEST contributor
       
       Please give this as level 2 issue as I done the animation and  update the design with website theme.

### CODE REVIEW

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@AmanKumar1115 it is good but, the description of their feedback comes under priority. We should not hover for it.
So, do one thing make it reverse. Feedback description should be visible first, by hovering it flips and showing their profile with social handles/place and more about them if required.
Also in feedback description include stars of their rating
Also reduce the size of the cards

**Comment by AmanKumar1115** [comment]
> @AmanKumar1115 it is good but, the description of their feedback comes under priority. We should not hover for it. So, do one thing make it reverse. Feedback description should be visible first, by hovering it flips and showing their profile with social handles/place and more about them if required. Also in feedback description include stars of their rating Also reduce the size of the cards

ok

**Comment by AmanKumar1115** [comment]
@jeevan10017  I  have done the changes 
You can verify and accept the merge.
Please increase  level  to level 2 also.

**Comment by jeevan10017** [comment]
> @jeevan10017 I have done the changes You can verify and accept the merge. Please increase level to level 2 also.
> 
> Sure, Reduce the size of the card, there is more blank space in the card. Keep stars in front of the card itself. And at the end of the feedback description write the authors name. Like ~author Give some of these colours to cards that match the website theme

copy that orange kind of color in website itself

**Comment by jeevan10017** [comment]
@nice work. Just one small change. In small screens the card is slightly aligned to the left side. Make it in the centre.
Instead of green once use fade of orange colour. If it looks good then keep it. Or else this one is OK

**Comment by AmanKumar1115** [comment]
> @AmanKumar1115 nice work. Just one small change. In small screens the card is slightly aligned to the left side. Make it in the centre. Instead of green once use fade of orange colour. If it looks good then keep it. Or else this one is OK

Done

**Review by jeevan10017 — APPROVED** [review]
👍

**Pull request merged**
