### PR TITLE
Added Calculators

### LINKED ISSUE #126: [Feature Request]: Add Calculators in services
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When creating a fitness-related application or tool, there are several calculators you can integrate to help users track their health, performance, and fitness goals. Here are some popular fitness calculators you might consider adding:

1. Body Mass Index (BMI) Calculator
Purpose: Helps users determine if they are underweight, normal weight, overweight, or obese based on their height and weight.
2. Basal Metabolic Rate (BMR) Calculator
Purpose: Estimates the number of calories a person needs to maintain their current weight at rest, which is useful for understanding daily caloric needs.
3. Caloric Needs Calculator
Purpose: Estimates the total daily caloric intake required to maintain or achieve specific fitness goals (e.g., weight loss, maintenance, or muscle gain).
4. Body Fat Percentage Calculator
Purpose: Estimates body fat percentage based on various measurements, which can help users track fat loss or muscle gain.

### Use Case

Integrating fitness calculators into a fitness-related application can significantly enhance user experience and engagement by providing personalized insights and actionable recommendations. For instance, the **Body Mass Index (BMI) Calculator** allows users to determine their weight category, serving as a foundation for setting realistic weight management goals, complemented by tailored content like workout plans for specific BMI categories. The **Basal Metabolic Rate (BMR) Calculator** helps users understand their calorie needs at rest, enabling informed dietary decisions, while the **Caloric Needs Calculator** allows users to estimate their daily caloric intake based on activity levels, facilitating effective weight management strategies. Lastly, the **Body Fat Percentage Calculator** helps users track their fat loss or muscle gain, offering valuable feedback that can motivate and guide their fitness journeys. Together, these features create a comprehensive tool that empowers users to monitor their health, customize their fitness plans, and achieve their goals more effectively.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by pavitraag**
# Title and Issue number 
Title : Add Calculators

Issue No. : #126 

Code Stack : Node.js

Close #126

# Video (mandatory)

https://github.com/user-attachments/assets/ed6dac8f-c109-44bc-9203-5f47e9f38860

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@pavitraag can you implement this in the bot, using json.
Kindly refer to the existing code of BMI Calculator init.

**Comment by pavitraag** [comment]
Can you explain me exactly what I shld do

**Comment by jeevan10017** [comment]
> Can you @jeevan10017 explain me exactly what I shld do
> 
> Is it like u want implementation in bot also or this whole thing you want in only bot
> And I didnt get about y to refer the existing code of BMI Calculator init. Is my calculations wrong?

Make the whole thing in bot.
creating a separate page for it, not seems good.

**Comment by pavitraag** [comment]
@jeevan10017 can i keep this in services as fitcalc because i am unable to keep this in chatbot

**Comment by jeevan10017** [comment]
@pavitraag integrate it in footer

**Comment by jeevan10017** [comment]
@pavitraag update?

**Pull request closed without merging**
