### PR TITLE
Enhancement in the footer section

### PR DESCRIPTION
**Pull request by ShreyaSnehal**
# Footer Enhancement . Issue 38

Title :Enhancement of the Footer section

Issue No. :38

Code Stack : 

Close #<38>

# Video (mandatory)

previous footer:
image

new footer attached below:
image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@ShreyaSnehal resolve conflicts and reduce the spaces between.
Also make it responsive

**Comment by ShreyaSnehal** [comment]
I have resolved the conflicts . Please check it.

**Comment by jeevan10017** [comment]
> I have resolved the conflicts . Please check it.
> 

Make it responsive..

**Comment by jeevan10017** [comment]
@ShreyaSnehal updates?

**Comment by jeevan10017** [comment]
@ShreyaSnehal resolve conflicts

**Comment by jeevan10017** [comment]
@ShreyaSnehal Currently, I am closing this PR. Can you reopen the PR again?
Because i cant see the the deployed version

**Pull request closed without merging**
