### PR TITLE
 [Bug]: fix the heading issue in mobile view, issue no. #306 

### LINKED ISSUE #306: [Bug]: fix the heading issue in mobile view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Fix the issue of text not showing inmobile view

Assign me this under hacktoberfest and gssoc-ext.

### Expected behavior

Screenshot_2024-10-22-12-36-17-64_40deb401b9ffe8e1df2f1cc5ba480b12
The text heading should be visible.

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AE-Hertz**
# Title and Issue number 

Title : fix the heading issue in mobile view

Issue No. : #306 

Code Stack : CSS

Close #306 

# Screenshot:
Screenshot 2024-10-24 140845

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@AE-Hertz  resolve conflicts

**Comment by AE-Hertz** [comment]
@jeevan10017 i have requested for PR please review and merge . thank you.
 please assign me any other issues if any.

**Comment by AE-Hertz** [comment]
@jeevan10017 merge my PR pls, before anymore conflicts arises, resolving conflict is tedious work.

**Comment by jeevan10017** [comment]
@AE-Hertz ,sorry for late, this is the last. I will merge your PR first after resolve conflicts

**Comment by AE-Hertz** [comment]
@jeevan10017 hello, i have requested for a new PR #393 regarding this , cant resolve this further on this PR handle. if you can upgrade the level that would be appreciated. thank you.

**Comment by AE-Hertz** [comment]
i hope this new branch gets merged before anymore conflicts.

**Pull request closed without merging**
