### PR TITLE
Added the Dockerfile

### LINKED ISSUE #124: [Feature Request]: Dockerize the Application
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

### Use Case

Dockerfile leads to easy development and deployment process.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Title and Issue number 
fixes #124 

Issue No. : #124 

# Video (mandatory)

https://github.com/user-attachments/assets/f751bb96-4888-4f28-9d96-4c4b13efeb31

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Sami3160** [comment]
> # Title and Issue number
> 
> fixes #124
> 
> Issue No. : #124
> # Video (mandatory)
> 2024-10-09.14-56-05.mp4
> # Checklist:
> 
>     * [x]  I have mentioned the issue number in my Pull Request.
> 
>     * [x]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [x]  I have created a helpful and easy to understand `README.md` if its a new page/tech stack
> 
>     * [x]  I have gone through the  `contributing.md` file before contributing
> 
> 
> **Additional context (Mandatory )**
> 
> _**Are you contributing under any Open-source programme?**_
> 
>     * [x]  I'm a GSSOC-EXT contributor
> 
>     * [x]  I'm a HACKTOBERFEST contributor

do you thing any possible errors would come while running this docker containers?  if so then also add how to solve them in readme, and from where do we remove or add dependencies or packages? and if i do changes in my code then will it immediately reflect in my website or i need to build another image or something?

**Comment by Sami3160** [comment]
> # Title and Issue number
> 
> fixes #124
> 
> Issue No. : #124
> # Video (mandatory)
> 2024-10-09.14-56-05.mp4
> # Checklist:
> 
>     * [x]  I have mentioned the issue number in my Pull Request.
> 
>     * [x]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [x]  I have created a helpful and easy to understand `README.md` if its a new page/tech stack
> 
>     * [x]  I have gone through the  `contributing.md` file before contributing
> 
> 
> **Additional context (Mandatory )**
> 
> _**Are you contributing under any Open-source programme?**_
> 
>     * [x]  I'm a GSSOC-EXT contributor
> 
>     * [x]  I'm a HACKTOBERFEST contributor

also we need  to keep this repo beginner friendly so also add steps to install docker on  all platform with proper configuration,

**Comment by haseebzaki-07** [comment]
The purpose of the Docker containerization is to make the dependencies abstract from the development process as the docker will talke care of it . we just need to run the docker commands . whatever change you make in the application will reflect on the website on the specified ports. @Sami3160

**Comment by haseebzaki-07** [comment]
hey @Sami3160 I have updated the readme for docker installation process

**Review by Sami3160 — APPROVED** [review]

**Pull request merged**
