### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #266: [Documentation Update]: Enhancement Of Contributing.md
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The contributing.md looks is not in a structured manner. Also some sections are missing.

### Suggested Change

I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

Wanted to do the following changes :-

1) Enhance the project structure
2) Add project structure section
3) Add additional method of contributing through GitHub desktop section
4) Add good coding practices section
5) Add the help and support section
6) Add the pull request section
7) Add issue report process section

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by milansamuel609**
# [Documentation Update]: Enhancement Of Contributing.md #266

Title : CONTRIBUTING.md Updation

Done the following changes :-

1) Enhanced the project structure
2) Added code of conduct that was given in the project structure
3) Added need help with the basics section
4) Added project structure section
5) Added good coding practices section
6) Added the help and support section
7) Added the pull request section
8) Added issue report process section

Issue No. : [#266 ]

Code Stack :  Git

Close: [#266 ]

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have updated the CONTRIBUTING.md file through online github itself because while cloning it in the desktop there was some issue with the cloning with this repository. Like all the files are not cloning and also due to that not a single is visible while opening it in VS Code. That's why I have done it in Github online platform itself.

**Comment by jeevan10017** [comment]
@milansamuel609 add new things, but don't remove the old ones

**Comment by milansamuel609** [comment]
> @milansamuel609 add new things, but don't remove the old ones
Ok 👍 . I am sorry for the deletion of previous sections.

**Comment by milansamuel609** [comment]
Now I think my tests have passed. Really sorry for the inconvenience caused previously.

**Comment by milansamuel609** [comment]
I have enhanced it once again. Please check it once.

**Comment by milansamuel609** [comment]
Please check the changes once. If they are ok please kindly merge the PR.

**Comment by milansamuel609** [comment]
@jeevan10017  Please kindly add the gssoc extend label also

**Comment by milansamuel609** [comment]
@jeevan10017 Please add the gssoc ext label also

**Pull request merged**
