### PR TITLE
Added nutrition tracker feature

### LINKED ISSUE #76: [Feature Request]: Nutrition Tracking
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

IT allows users to log their meals by entering food items, portion sizes, and meal types through a user-friendly interface. Once logged, the application fetches nutritional information from a database or API, calculates total calories and macronutrients, and updates the user's daily intake on their dashboard. Users can review their meal history, edit or delete entries, and receive notifications if they approach their caloric goals. This feature promotes healthier eating habits by providing users with insights into their nutrition and helping them stay aligned with their dietary goals.

### Use Case

Sarah, a 28-year-old fitness enthusiast aiming to lose 10 pounds, uses the app's nutrition tracking feature to log her meals and receive instant nutritional information. The app sends reminders, provides visual insights into her eating habits, and connects her with a supportive community. This feature empowers Sarah to make informed dietary choices and enhances her accountability, increasing her chances of achieving her weight loss goal before her beach vacation.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by meghanakn473**
Title : Added nutrition tracker feature
IT allows users to log their meals by entering food items, portion sizes, and meal types through a user-friendly interface. Once logged, the application fetches nutritional information from a database or API, calculates total calories, and updates the user's daily intake on their dashboard.

Issue No. : #76

Close #76 

# Video (mandatory)

https://github.com/user-attachments/assets/6adc8c9d-26b0-4702-8865-868d799928d5

# Checklist:

- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [ X] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***

- [ yes] I'm a GSSOC-EXT contributor
- [ yes] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@meghanakn473, are you using GPT for all? Then why is it necessary to change all the files in the App.jsx and Navbar

**Comment by jeevan10017** [comment]
@meghanakn473 any  update?

**Comment by meghanakn473** [comment]
> @meghanakn473, are you using GPT for all? Then why is it necessary to change all the files in the App.jsx and Navbar

Where did I go wrong? Can u specify please? @jeevan10017

**Comment by jeevan10017** [comment]
> @meghanakn473 Could you send the demo video of where you had linked this page? And what is the necessary change in the app. jsx from double quote to single quote and jumbling the lines of code?

Update?

**Pull request closed without merging**
