### PR TITLE
[FEAT] Added Team Section Carousel to About Page

### LINKED ISSUE #326: [Feature Request]: Adding a Carousel to Show team members at About us Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "About Us" page currently lacks an engaging way to showcase our team members. I propose adding a carousel that will display the profiles of our team members, enhancing user experience and providing visitors with a more dynamic view of our staff.

### Use Case

- Improve the visual appeal of the "About Us" page.
- Allow visitors to easily learn about our team without overwhelming them with information.
- Enhance engagement by making the page more interactive.

### Benefits

_No response_

### Add ScreenShots

https://github.com/user-attachments/assets/20bda762-95b0-47d9-8abf-13372a241e9e

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by IkkiOcean**
Title : Added Team Section Carousel to About Page

Description: 
This PR introduces the TeamSection component to the About page, showcasing our team members and their expertise. The component includes a responsive design that adapts to different screen sizes and supports both light and dark modes.

- Close #326 

# Video (mandatory)

https://github.com/user-attachments/assets/9a7e7a9b-081d-43e9-8577-52d9d41a8011

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing
- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by IkkiOcean** [comment]
Sir please add level 3 after looking into my work.

**Comment by jeevan10017** [comment]
@IkkiOcean good work. small changes align stars correctly. And in mobile view cards were tilting to on side gradually

**Comment by IkkiOcean** [comment]
@jeevan10017 can you share me the Screenshot. I don't see stars alignment issue in my device. It will help 

Plus wht do you mean my card tilting?

**Comment by jeevan10017** [comment]
Cards tilting means cards were not alligned to center

**Comment by IkkiOcean** [comment]
@jeevan10017 done with the required changed. You may check now.

WhatsApp Image 2024-10-26 at 18 16 17

the mobile view...

**Pull request merged**
