### PR TITLE
new page added, healthtips

### LINKED ISSUE #41: [feature]: Create Health tips page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we tap on the logo of the website it wont redirect back to home

### Expected behavior

The logo button should redirect to the home page

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Jay-1409**
# Title and Issue number 

Title : HealthTips Page Created
Issue No. : #41 

Code Stack : React, Css.

Close #41 

# Images
image

# Checklist:

- [*] I have mentioned the issue number in my Pull Request.
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [*] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [*] I'm a GSSOC-EXT contributor
- [*] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@Jay-1409, good start; make all images a fixed ratio to visible all image section. Also, make sure to make the page theme the same as the existing website. And also, could you make sure these images have no copyright issues?
Also merge that title icon link which issue was created earlier

**Comment by Jay-1409** [comment]
Oh it!!

**Comment by Jay-1409** [comment]
I have changed the links in order to avoid any copyright issues, and i have set the images too and have made the logo --> home redirect functioning too. please check it. ;)

**Review by jeevan10017 — COMMENTED** [review]
Good work!

**Pull request merged**
