### PR TITLE
Feature/google auth

### PR DESCRIPTION
**Pull request by samriddhitiwary**
# Title and Issue number 

Title :Login Page Improvement Request

Issue No. : #18

Code Stack : 

Close #<#18>

# Video (mandatory)

https://github.com/user-attachments/assets/c339f5f1-8c7f-4cad-88f6-e416a62a216e

# Checklist:

- [ x] I have mentioned the issue number in my Pull Request.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x ] I'm a GSSOC-EXT contributor
- [ x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by samriddhitiwary** [comment]
@jeevan10017 I have fixed the issue and tested the URL:https://deploy-preview-73--befiteveryday.netlify.app/  and it's working fine could you please review it.

**Comment by samriddhitiwary** [comment]
@jeevan10017 If code meet your requirements than could please add the gssoc-ext level3 and hacktoberfest labels here too

**Review by jeevan10017 — APPROVED** [review]
@samriddhitiwary google authentication is pre-built in firebase. So, it can't be level3 unless you create with email/ph no password.

**Comment by samriddhitiwary** [comment]
@jeevan10017 Thank you

**Pull request merged**
