### PR TITLE
added gsap animation to navbar and hero section |fixes #241

### LINKED ISSUE #241: [Feature Request]: 🚀 [UI Enhancement ] -Adding Gsap Animations to landing page for better UI experinece | gssoc-ext | level 3
### Is there an existing issue for this?

- [X] I have searched the existing issues

### *i will first integrate GSAP to react then create UseEffect for rendering animation when page is loaded , inside useEffect i will create a gsap context that make sure that animations are played only when the component is already rendered than i will use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations*

please asign this to me under  gssoc-ext level 3

### Use Case

when the website is loaded then user will see a sliding down navbar with its elemnts having  stagger effect and also hero section text will be having effect of sliding from left and right

### Benefits

it will give user more engaging experience

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Hamza1821**
# Title and Issue number 

Title : added gsap animation to navbar and hero section

Issue No. : #241 

Code Stack : Gsap

Close #241

# Video (mandatory)

https://github.com/user-attachments/assets/0ddcc679-1fc2-4cc7-bbbb-a8a53bdd5e44

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Hamza1821** [comment]
Please merge this pr

**Review by jeevan10017 — APPROVED** [review]

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@Hamza1821 Reraise a PR. Its failing a deploy preview.

**Comment by jeevan10017** [comment]
@Hamza1821 Deploy Preview for befiteveryday failed.

**Comment by Hamza1821** [comment]
How to resolve deploy failed

**Pull request closed without merging**
