### PR TITLE
Feature/google auth

### PR DESCRIPTION
**Pull request by samriddhitiwary**
# Title and Issue number 

Title :Login Page Improvement Request

Issue No. : #18

Code Stack : 

Close #<#18>

# Video (mandatory)

https://github.com/user-attachments/assets/c339f5f1-8c7f-4cad-88f6-e416a62a216e

# Checklist:

- [ x] I have mentioned the issue number in my Pull Request.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x ] I'm a GSSOC-EXT contributor
- [ x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@samriddhitiwary, can you send PR again? The previous one is fails in deploy.

**Comment by samriddhitiwary** [comment]
@jeevan10017 Ok

**Comment by samriddhitiwary** [comment]
@jeevan10017 thank you for merging could please add all the label in the PR also otherwise it won't count it

**Comment by jeevan10017** [comment]
I have already labeled in #73

**Review by jeevan10017 — COMMENTED** [review]
Merged in another #74 PR

**Comment by samriddhitiwary** [comment]
@jeevan10017 Thank you soo much

**Pull request merged**
