### PR TITLE
Added Personalized Workout and Diet Recommendation System

### LINKED ISSUE #187: [Feature Request]: Personalized workout and diet plans suggestor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature will provide users with personalized workout and diet plans based on their individual fitness goals, body type, and health conditions. The system will use input data such as age, weight, fitness level, dietary preferences, and health conditions to generate customized exercise routines and meal plans. The suggestions will be tailored for users aiming for different goals, such as weight loss, muscle gain, or general fitness maintenance. It will also take into account dietary restrictions (e.g., vegetarian, vegan, gluten-free) and exercise preferences (e.g., strength training, cardio, yoga).

### Use Case

- Personalized Fitness Plans: Users can input their fitness goals, and the system will generate tailored workout routines and diet suggestions to help them achieve those goals.
- Health and Nutrition Monitoring: Users with specific dietary needs or fitness constraints (e.g., due to medical conditions) can receive suggestions that align with their health requirements, ensuring they stay on track without compromising their well-being.

### Benefits

- ailored Fitness and Nutrition: Users receive personalized workout and diet recommendations that are customized to their goals, fitness level, and dietary preferences, ensuring the plans are effective and sustainable.
- Convenience: With automatically generated plans, users save time and effort in researching exercises or meals that fit their needs, making it easier to maintain a healthy lifestyle.
- Health Optimization: By providing workout and diet plans that take into account the user's health conditions and preferences, the feature promotes balanced, sustainable improvements in both fitness and nutrition.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
# Title and Issue number 

Title : Added Personalized Workout and Diet Recommendation System

Issue No. : #187

Code Stack : React, Flask

Close #187

# Video (mandatory)
https://drive.google.com/file/d/12E-xvWaw51UxU5ntPsPcYNuaHKRas8UE/view?usp=sharing

Screenshots:
Image
Image
Image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@jeevan10017 Please review and let me know the comments!

**Review by jeevan10017 — CHANGES_REQUESTED** [review]
@J-B-Mugundh resolve merge conflicts and add some design to it.

**Comment by J-B-Mugundh** [comment]
@jeevan10017 

I've updated the styles. Added glassmorphic effect and a bg image. Will this be fine?

image

**Comment by jeevan10017** [comment]
@J-B-Mugundh Right now, I am closing this PR because it's having an issue with the deploy preview option is not available. Re-send the PR again.

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh Right now, I am closing this PR because it's having an issue with the deploy preview option is not available. Re-send the PR again.

Okay!

**Pull request closed without merging**
