### PR TITLE
bmi-cal-added

### PR DESCRIPTION
**Pull request by NK-Works**
# Title and Issue number 

Title : Added BMI calculator

Issue No. : #248 

Code Stack : https://github.com/NK-Works/FitFlex/blob/bmi/src/components/BMICalculator.jsx

Screenshot:
image

# Video (mandatory)
https://github.com/user-attachments/assets/e1ad68ca-1cff-41fd-ac4d-4e7eb5208985

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@NK-Works I'm sorry for the inconvenience. It is already present in the Chatbox. Even though, this design not seems good.

**Comment by NK-Works** [comment]
@jeevan10017 I showed the design during issue creation maybe I could have rejected it then :( wasted my efforts 😞

**Comment by jeevan10017** [comment]
@NK-Works OK, Do one thing. Link it to a footer named "BMI Calculator." The popup model/ form should appear when the user clicks on this. So, in this form, the user can calculate his BMI.
create another New PR for this

**Comment by NK-Works** [comment]
@jeevan10017 I have added the BMI Calculator with a link... Hope this satisfies you :)
Check PR #311

**Comment by jeevan10017** [comment]
> @jeevan10017 I have added the BMI Calculator with a link... Hope this satisfies you :) Check PR #311

create new PR for this

**Pull request closed without merging**
