### PR TITLE
Local Storage Addition for User Data Storing and ChatBot Responsiveness | Issue #165

### LINKED ISSUE #165: Addition of Persistent Storage for UserData | ChatBot Enhancement | Optimisation of Recurrence Of Questioning
I want to add the Persistent Storage for the optimisation of UserData Flow for ChatBot Flow.
In this, I am going to implement the sessionStorage / localStorage for the userData storing that results in optimization of ChatBot Flow.

**Contributor Information**
Please check if you are a contributor from:
- [X] GSSoC-ext
- [X] Hacktoberfest

### PR DESCRIPTION
**Pull request by Shariq2003**
# Title and Issue number 

Title : Local Storage Addition for User Data Storing | Issue #165

Issue No. : #165 

Code Stack : Same 

Close #165 

# Video (mandatory)

https://github.com/user-attachments/assets/f065a909-5699-4462-befd-d43efa165de2

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@Shariq2003 make it responsive..

**Comment by Shariq2003** [comment]
> @Shariq2003 make it responsive..

Okay working

**Comment by Shariq2003** [comment]
> @Shariq2003 make it responsive..

@jeevan10017 please check this

https://github.com/user-attachments/assets/934be827-9b11-4b80-872a-bc1e8349eaaf

**Review by jeevan10017 — APPROVED** [review]

**Comment by Shariq2003** [comment]
@jeevan10017 sir, i have two features

1. Local Storage and
2. Responsiveness

**Comment by NEGRAH-S** [comment]
@MastanSayyad , not much changes, label  must be changed back to Level 2

**Pull request merged**
