### PR TITLE
Enhance the Blogs Page | Issue #233

### LINKED ISSUE #233: [Feature Request]: Redesigning of Blog Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image

### Use Case

.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Shariq2003**
# Title and Issue number 

Title : Enhance the Blogs Page

Issue No. : #233 

Code Stack : Same

Close #233 

# Video (mandatory)

https://github.com/user-attachments/assets/9e3ec2d1-5d96-4123-ab8b-bdba122b1769

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by Shariq2003** [comment]
@jeevan10017 sir, review and merge

**Comment by jeevan10017** [comment]
> @jeevan10017 sir, review and merge

Make a quality contribution. 
Don't do just for the sake of contribution for the leaderboard.
Have you seen its responsiveness?
Font family?
What reference images you have submitted in issue?

**Comment by jeevan10017** [comment]
@Shariq2003 it entirely seems to GPT code

**Comment by Shariq2003** [comment]
> > @jeevan10017 sir, review and merge
> 
> Make a quality contribution. Don't do just for the sake of contribution for the leaderboard. Have you seen its responsiveness? Font family? What reference images you have submitted in issue?

Wait sir, I am correcting completely with proper code and responsiveness

**Comment by Shariq2003** [comment]
@jeevan10017 sir, please review and merge this

**Comment by jeevan10017** [comment]
@Shariq2003, can you send the updated video reference with a responsive one? I am holding this because of this PR  showing the blank deploy preview.

**Comment by Shariq2003** [comment]
> @Shariq2003, can you send the updated video reference with a responsive one? I am holding this because of this PR showing the blank deploy preview.

see above

**Comment by Shariq2003** [comment]
> > @Shariq2003 it entirely seems to GPT code
> 
> @jeevan10017 sir, now, please review this Fully Responsive
> 
>  bandicam.2024-10-25.21-27-00-110.mp4

this one

**Comment by Shariq2003** [comment]
> @Shariq2003, can you send the updated video reference with a responsive one? I am holding this because of this PR showing the blank deploy preview.

Sir that's the issue of BUG in Footer

**Comment by Shariq2003** [comment]
@jeevan10017 Check this #368

**Comment by jeevan10017** [comment]
@i don't know why it crashed; your deployment preview is not working. Recently, the update blog has been integrated, but your demo video is not present.

**Comment by Shariq2003** [comment]
> @i don't know why it crashed; your deployment preview is not working. Recently, the update blog has been integrated, but your demo video is not present.

Because you merged the PR of someone that have the previous blog page, that raises conflicts in my PR.

OKay fixing

**Comment by Shariq2003** [comment]
https://github.com/user-attachments/assets/165ff4d6-18b3-4381-bd73-2ad9c0bddd69

@jeevan sir, I have fixed all the conflicts and issues, but now you have to merge my PR before anyone else because if anyone has a previous blog page code, that will raise conflicts in my PR again.

**Comment by Shariq2003** [comment]
@jeevan10017 sir please review.

**Comment by jeevan10017** [comment]
In previous times, i have merged, so that users can upload a blog. Where is it?

**Comment by Shariq2003** [comment]
> In previous times, i have merged, so that users can upload a blog. Where is it?

yup adding.

**Comment by Shariq2003** [comment]
@jeevan10017 check now.

**Pull request merged**
