### PR TITLE
Addition Of ChatBot | Issue #37

### LINKED ISSUE #37: [Feature Request]: Addition of Customer Support | Chatbot Bubble
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image

We can add a Chatbot Suport for Personalize support to customer similar to the above image.
Initially, I can add the Bubble Chatbot Icon on the Website,
Later, that can extend to integrate with the bot in the future to communicate with the customer.

### Use Case

Enhance the UI and UX

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Shariq2003**
# Title and Issue number 

Title : Addition Of ChatBot | Issue #37

Issue No. : #37 

Code Stack : 

Close #37 

# Video (mandatory)

https://github.com/user-attachments/assets/fa0ed06c-c546-47c3-bc4a-d4bcb6b6c415

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@Shariq2003 only give 5 mins and also integrate BMI calculator init. 
as in this doc 
https://www.npmjs.com/package/react-simple-chatbot
use GPT for fast 
image

**Comment by Shariq2003** [comment]
Okay @jeevan10017 give me 5 mints.

**Comment by Shariq2003** [comment]
@jeevan10017 check now.

**Comment by jeevan10017** [comment]
@Shariq2003 lacks responsiveness but, OK we can do it later.

**Review by jeevan10017 — APPROVED** [review]

**Comment by Shariq2003** [comment]
Okay , will make the changes in the next issue.

@jeevan10017 what I am thinking for enhancing the chatbot by implementing a persistence data storage that prevent the recurrence of the chatbot to ask user details again and again everytime whenever user visits website.

What can I do is, thinking of storing the user entered data at first time into the session storage or local storage that enhance the chatbot flow and optimised the chatbot.

Can I create an issue for this

**Comment by jeevan10017** [comment]
@Shariq2003 create new issue for this

**Comment by jeevan10017** [comment]
@Shariq2003 Make this PR again, i am reverted it, bcoz of the dependencies created a major issue to the repo.
Don't send pakagelock.json for next time.

**Pull request merged**
