### PR TITLE
Fix: The values of Height Weight during BMI calculation change

### LINKED ISSUE #243: [Bug]: The values for height and weight do not change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The values for height and weight in the FitFlex Customer Support does not change with every new request in the same chat.

### Expected behavior

With every request for BMI Calculation, the height and weight need to be updated and show the new BMI

### Add ScreenShots

https://github.com/user-attachments/assets/f5eebeca-0a6d-43b1-9712-114929d83936

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sank8-2**
# Title and Issue number 

Title: Fix: The values of Height Weight during BMI calculation change

Issue No.: #243 

Code Stack: ReactJS

Close #243 

# Video (mandatory)

https://github.com/user-attachments/assets/bb030122-62ca-4358-ae8c-99897d4ebac5

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [X] I have gone through the  `contributing.md` file before contributing

 

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@sank8-2, why do you want to change the details of height and weight again?

**Comment by sank8-2** [comment]
In the array that calculates bmi, if we try to recalculate bmi according to the chatbot flow, the values do not update and bmi is shown of the previous values of height and weight.

**Comment by sank8-2** [comment]
@jeevan10017 You can check Issue #243 for what is actually happening

**Comment by jeevan10017** [comment]
@sank8-2 am saying that, if the user entered his details first ,then why does he want to change it.
Anyways, do additions that give the suggestions, procedure to workout based on their BMI.

**Comment by sank8-2** [comment]
@jeevan10017 I'm not saying that changes for weight height from user details.
In the chatbot, the flow is
>Calculate BMI
<Yes
>Enter Height
<100
>Enter Weight
<50
>Your BMI is something
>Do you want to recalculate?
<Yes
>Enter height
<120
>Enter Weight
<60
>Your BMI is something

So, while this happens when the user is prompted the second time for height and weight, the BMI is calculated based off the first values of height and weight.
And an user may come upto this flow if he wishes to calculate the BMI of someone else in the same flow

**Comment by jeevan10017** [comment]
> @jeevan10017 I'm not saying that changes for weight height from user details.
> In the chatbot, the flow is
> >Calculate BMI
> <Yes
> >Enter Height
> <100
> >Enter Weight
> <50
> >Your BMI is something
> >Do you want to recalculate?
> <Yes
> >Enter height
> <120
> >Enter Weight
> <60
> >Your BMI is something
> 
> So, while this happens when the user is prompted the second time for height and weight, the BMI is calculated based off the first values of height and weight.
> And an user may come upto this flow if he wishes to calculate the BMI of someone else in the same flow

Ok, also add the next procedure/suggestions of their calculated BMI.

**Comment by sank8-2** [comment]
@jeevan10017 
Ya lemme try that

**Comment by sank8-2** [comment]
@jeevan10017 Hi, I have added the response according to the BMI, please let me know if any changes are needed.

**Pull request merged**
