### PR TITLE
BMI Calculator Added New Linked

### LINKED ISSUE #248: [Feature Request]: Add a BMI calculator
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a BMI calculator

### Use Case

image
in this position
can be used to calculate the BMi of the body builders

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by NK-Works**
# Title and Issue number 

Title : BMI Calculator with new link

Issue No. : #248

Code Stack : https://github.com/NK-Works/FitFlex/blob/bmi/src/components/BMICalculator.jsx

Close #248

# Video (mandatory)

https://github.com/user-attachments/assets/e12fd975-fa48-46e8-a59f-7eaca30696d4

Screenshots:
image
image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

### CODE REVIEW

**Comment by jeevan10017** [comment]
@NK-Works Do you have an idea of creating this in modal type instead of routing in new page.

**Comment by NK-Works** [comment]
@jeevan10017 do mean as a pop-up?

**Comment by jeevan10017** [comment]
> @jeevan10017 do mean as a pop-up?
Yeah like this, 

image

**Comment by NK-Works** [comment]
@jeevan10017 will do that then

**Comment by jeevan10017** [comment]
> @jeevan10017 will do that then

If you have an idea of creating a modal, then. do it

**Pull request closed without merging**
